language: go

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - git clone https://github.com/cokidd/personal-pages.git

script:
  - hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "cokidd"
  - git config user.email "okidingme@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://$token@${GH_REF}" master:master
  - git push --quiet "https://$token@${GH_REF}" master:master --tags

env:
 global:
   - GH_REF: cokidd/cokidd.github.io.git

deploy:
  provider: pages 
  skip-cleanup: true
  local-dir: public 
  github-token: $token 
  on:
    branch: master 
