sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/cokidd/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    on:
        branch: master
    local_dir: public
    repo: cokidd/cokidd.github.io
    fqdn: 
    target_branch: master
    email: okidingme@gmail.com
    name: cokidd
